import type { Metadata } from "next";
// import { GoogleTranslate } from "@/components/googleTranslate/Translate";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import '@fortawesome/fontawesome-free/css/all.css';
import "@glidejs/glide/dist/css/glide.core.min.css";
import Script from "next/script";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      {/* <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta> */}
      </head>
      <body className={`${inter.className} bg-[#101726] text-white`}>
        
        {children}
        {/* <Footer /> */}
        {/* <script src="https://kit.fontawesome.com/94794741f1.js"></script> */}
        <Script
                id="google-translate-script"
                // strategy="afterInteractive" // Load after interactive content
                src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
            />
            
      </body>
    </html>
  );
}
