import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });
import '@fortawesome/fontawesome-free/css/all.css';
import "@glidejs/glide/dist/css/glide.core.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-900 text-white`}>{children}
        <Footer />
        {/* <script src="https://kit.fontawesome.com/94794741f1.js"></script> */}
      </body>
    </html>
  );
}
